### ISSUE TITLE
Ensure safety limits work in software 

### ISSUE THREAD

**Issue by omegabytes** [rLoopTeam/eng-software-pod#109]
(i.e. move planner terminates on interrupt)

**Comment by SafetyLok** [comment]
If we move a distance and that distance exceeds the safe travel and we hit the end stop switches we much make sure that the stepper system aborts its current move immediately.

We should check this with a DSO or similar to check the timing in software from interrupt to movement abort. Technically it should be no greater than the minimum step time which is currently 50us.

**Comment by rjvyas** [comment]
@SafetyLok I've written functions to issue fault flags if either of the limit switches for the brakes are switched on. Where do I write code that will actually abort the current move immediately based on the fault flags? Which file will that function go in? My understand is that based on the fault flags, we need to switch into "case BRAKE_STATE__MOVE_STOPPED". Is this correct?

**Comment by SafetyLok** [comment]
Done, movement planner stops on ISR
