### ISSUE TITLE
Report all details of brake position, etc back to GS.

### ISSUE THREAD

**Issue by omegabytes** [rLoopTeam/eng-software-pod#110]

**Comment by Gatsu47** [comment]
Can I have some more info on this issue? Which parameters need to be reported and where is the interface module with the GS? Thanks

**Comment by m4rol** [comment]
send back to GS
- Right Brake deployment percentage 
- Left Brake deployment percentage
- Right MLP value
- Left MLP value
- Limit Switch 1-4 - current state
- Distance of the Right brake assembly relative to I-beam
- Distance of the Left brake assembly relative to I-beam

**Comment by SafetyLok** [comment]
Done and tested on RPOD_CONTROL app, GS will follow as packets have been defined and tested.
