### ISSUE TITLE
Allow GS to check the sensors, data, error counters, flags, etc.

### ISSUE THREAD

**Issue by omegabytes** [rLoopTeam/eng-software-pod#125]

**Comment by jennylin** [comment]
Acceptance Criteria:

- Make sure each distance laser sensor is connected to RM48, show that the ground station is receiving distance from laser distance sensors through the RM48 and Pi
- Put something at a known distance away
- Make sure each distance sensor displays distance
- Move thing closer or further and make sure distance changes
- Disconnect everything and retrieve and verify dumped data

**Comment by SafetyLok** [comment]
Done, added contrast sensor interface.
