### ISSUE TITLE
Provide low level read functions to monitor the Thermal and RPM performance + any other params

### ISSUE THREAD

**Issue by omegabytes** [rLoopTeam/eng-software-pod#133]
Bonus points for changing direction setting bit in ASI, maybe throttle map too.

**Comment by omegabytes** [comment]
Can we clean up the title and provide the details in this definition?

**Comment by nazneenk** [comment]
Functions are provided to read controller temperature, motor rpm.  More functions to read/write other parameters can be easily added with the modbus protocol implemented.

**Comment by SafetyLok** [comment]
Done and tested
