### ISSUE TITLE
Interface with the OptoNCDT sensors.

### ISSUE THREAD

**Issue by omegabytes** [rLoopTeam/eng-software-pod#145]

**Comment by dean9** [comment]
This was completed using the analog output here https://github.com/rLoopTeam/makers-hdk.  we'll need to use the digital output on the pod though, Frank did it this way with HE testbed.

**Comment by dean9** [comment]
https://github.com/frank26080115/rPodDotC optoncdt.c, optoncdt.h

**Comment by SafetyLok** [comment]
Done using digital interface.
