### ISSUE TITLE
Design and test I2C read interface

### ISSUE THREAD

**Issue by edchanonline** [rLoopTeam/eng-software-pod#168]
The TSYS01 device needs a layer written to comm with the I2C channel to be able to issue an address and read a register.

**Comment by jennylin** [comment]
Acceptance Criteria:
- With TSYS01 connected to RM48, show that the ground station is receiving temperature from TSYS01 through the RM48 and Pi
- Clasp hand around sensor and watch number go up
- Remove hand from sensor and watch number go down
- Disconnect everything and retrieve and verify dumped data

**Comment by SafetyLok** [comment]
Done.
