### ISSUE TITLE
Provide functions to configure the internal mux

### ISSUE THREAD

**Issue by omegabytes** [rLoopTeam/eng-software-pod#21]

**Comment by edchanonline** [comment]
Looking at the datasheet - https://goo.gl/JNkGxE
I am not sure here and how to configure the internal mux; not specified anywhere

**Comment by edchanonline** [comment]
http://processors.wiki.ti.com/images/9/98/RM48_CNCD_SchematicRevA.pdf
Pinout

**Comment by SafetyLok** [comment]
Abandoned, not needed.
