### ISSUE TITLE
Provide a function to read the cal data off the device, check the CRC is valid.

### ISSUE THREAD

**Issue by omegabytes** [rLoopTeam/eng-software-pod#22]

**Comment by edchanonline** [comment]
- [x] read the cal data - Done 

Please look at ms5607 short-live feature branch.

TODO check the CRC is valid

**Comment by SafetyLok** [comment]
Let me show you the example of CRC this because it has to be tied in with the RM48 Bank 7 EEPROM.

**Comment by edchanonline** [comment]
@SafetyLok , @chipxsd and us went ahead and added crc4 function. Please take a look when you have a chance
