### ISSUE TITLE
Verify the functionality of Undervolt trip configuration

### ISSUE THREAD

**Issue by omegabytes** [rLoopTeam/eng-software-pod#59]
Test if this function works with the IRQ. Log the results.

**Comment by jennylin** [comment]
Acceptance Criteria: 
- Using Battery testbed A, from RM48 ask module to discharge and verify voltage has dropped by multimeter
- Using Battery testbed A, from RM48 ask module to discharge and keep discharging until we hit our Undervolt trip threshold (set it a little higher than actual threshold for testing). Verify with multimeter that we stop discharging when threshold is hit
- Using Battery testbed A, start with a battery below Undervolt threshold. Plug in, attempt to discharge, and verify with multimeter that we don’t actually discharge

Battery testbed A: ATA6870N connected to 2 RC batteries (2 x 3 module x 1 cell each = 6 cells)

**Comment by SafetyLok** [comment]
ATA device abandoned.
