### ISSUE TITLE
Create a basic driver for this to generate a pulse to the DC/DC converter from power node

### ISSUE THREAD

**Issue by omegabytes** [rLoopTeam/eng-software-pod#67]
DO not use a timer, use a state machine / main process loop

**Comment by jennylin** [comment]
Acceptance Criteria:
- When power is on, with oscilloscope or logic analyzer, see regular interval of square signals coming through
- When power is off, make sure it flatlines to 0
- Start again, with state machine running, turn power off and make sure it flatlines to 0 and stays 0
- Start again, but this time, run several of the other acceptance criteria tests first
- Then ask for power shutoff and make sure it flatlines to 0
- Run through multiple scenarios of things happening in power node before asking for power shutoff

**Comment by SafetyLok** [comment]
Done for FCU
