### ISSUE TITLE
Ensure any faults from ATA6870 comes up to this layer

### ISSUE THREAD

**Issue by omegabytes** [rLoopTeam/eng-software-pod#74]

**Comment by SafetyLok** [comment]
The ATA6870 can have many different types of faults, from devices missing to voltage readings out of tolerance. We should make an effort to ensure any faults on the ATA6870 layer come up to the BMS layer and that we do not attempt to keep processing the BMS system if errors exist. We should deal with handling errors correctly, such as to alert the GS.

**Comment by SafetyLok** [comment]
Done and also moved to BQ76 part
