### ISSUE TITLE
Short State list

### ISSUE THREAD

**Issue by omegabytes** [rLoopTeam/eng-software-pod#86]
I imagine states like (this is just a very short list):
                12.5.1 Init
        12.5.2 Start Sample TSYS01
        12.5.3 Wait TSYS01 busy
        12.5.4 Read TSYS01
        12.5.5 Start MS5607
        12.5.6 Wait MS5607, etc.
        12.5.7 Start ATA6870 Cell voltage measurement
        12.5.8 Read Cell Voltages
        12.5.9 Check voltages within tolerance
        12.5.10 Cell balancing state actions
        12.5.11 Charger Start
        12.5.12 Charger Measure voltage and current
        12.5.13 Battery safety tasks, read temp, check voltages, etc.
        ....
        12.5.x Power Up, Power Down, fault handling.

I imagine the state machine will have various states that are only active during various phases of flight or ground station control. Such as when the GS activates battery charge mode, etc.

**Comment by m4rol** [comment]
keep in mind that we don't have the battery packs for the test weekend, so all states related to them should be excluded for the time being. maybe just comment them out
